package vdel.symbols;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 17 12:22:27 BST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class BaseSym {
  /* terminals */
  public static final int GREATERTHAN = 30;
  public static final int AGENT = 8;
  public static final int DIVIDE = 22;
  public static final int GREATERTHANEQUAL = 31;
  public static final int LBRACKET = 43;
  public static final int KNOWS = 9;
  public static final int EQUALS = 20;
  public static final int DOUBLEEQUALS = 27;
  public static final int DOUBLE = 7;
  public static final int INTEGER = 6;
  public static final int NOTEQUAL = 32;
  public static final int LPAREN = 41;
  public static final int SEMI = 40;
  public static final int DYNAMIC_KW = 16;
  public static final int INT = 13;
  public static final int EPISTEMIC_KW = 17;
  public static final int MINUS = 24;
  public static final int RPAREN = 42;
  public static final int LESSTHANEQUAL = 29;
  public static final int NOT = 36;
  public static final int AND = 33;
  public static final int LESSTHAN = 28;
  public static final int OR = 34;
  public static final int COMMA = 45;
  public static final int ATOM_IDENTIFIER = 3;
  public static final int IMPLIES = 35;
  public static final int BEGIN = 38;
  public static final int PLUS = 23;
  public static final int MULTIPLY = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RBRACKET = 44;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int SQUARE = 26;
  public static final int EVERYBODYKNOWS = 11;
  public static final int DISTKNOWLEDGE = 10;
  public static final int MOD = 37;
  public static final int CONSTRAINT_KW = 15;
  public static final int OBSERVES = 12;
  public static final int AGENT_IDENTIFIER = 4;
  public static final int ENUM = 14;
  public static final int END = 39;
  public static final int SQUAREROOT = 25;
  public static final int FALSE = 19;
  public static final int IDENTIFIER = 5;
}

