package vdel.symbols;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 06 23:12:18 BST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CESym {
  /* terminals */
  public static final int MOD = 21;
  public static final int AND = 17;
  public static final int SQUARE = 7;
  public static final int MULTIPLY = 4;
  public static final int PLUS = 2;
  public static final int OR = 18;
  public static final int RPAREN = 9;
  public static final int SEMI = 10;
  public static final int NOTEQUAL = 16;
  public static final int NOT = 20;
  public static final int IDENTIFIER = 24;
  public static final int DOUBLEEQUALS = 11;
  public static final int TRUE = 25;
  public static final int IMPLIES = 19;
  public static final int LPAREN = 8;
  public static final int GREATERTHANEQUAL = 15;
  public static final int LESSTHAN = 12;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int SQUAREROOT = 6;
  public static final int FALSE = 26;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTEGER = 22;
  public static final int LESSTHANEQUAL = 13;
  public static final int GREATERTHAN = 14;
  public static final int DOUBLE = 23;
}

