package vdel.symbols;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 17 14:46:31 BST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ECESym {
  /* terminals */
  public static final int MOD = 22;
  public static final int AND = 18;
  public static final int SQUARE = 7;
  public static final int MULTIPLY = 4;
  public static final int PLUS = 2;
  public static final int OR = 19;
  public static final int RPAREN = 9;
  public static final int NOTEQUAL = 17;
  public static final int SEMI = 11;
  public static final int NOT = 21;
  public static final int IDENTIFIER = 26;
  public static final int DOUBLEEQUALS = 12;
  public static final int TRUE = 30;
  public static final int IMPLIES = 20;
  public static final int EVERYBODYKNOWS = 25;
  public static final int LPAREN = 8;
  public static final int GREATERTHANEQUAL = 16;
  public static final int KNOWS = 23;
  public static final int BRACKET = 10;
  public static final int ATOM_IDENTIFIER = 27;
  public static final int LESSTHAN = 13;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int SQUAREROOT = 6;
  public static final int FALSE = 31;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int DISTKNOWLEDGE = 24;
  public static final int INTEGER = 28;
  public static final int LESSTHANEQUAL = 14;
  public static final int GREATERTHAN = 15;
  public static final int DOUBLE = 29;
}

